name: buku_barang
description: Buku Barang BB by Natanael - Pencatatan Barang Masuk & Upah Pekerja
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
